/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.controls;

/**
 *
 * @author Stephan_2
 */
@SuppressWarnings("serial")
public class InformationPanel extends javax.swing.JPanel {
    private String graphInformations = "";
    /**
     * Creates new form InformationPanel
     */
    public InformationPanel() {
        initComponents();
        this.setGraphinformationText();
        this.informationLabel.setText(graphInformations);
        
    }
    private void setGraphinformationText(){
        this.graphInformations =  "<html><p>This Graphviewer</p><p>was implemented by:</p></br>"+"<p>Stefan Berger,</p>"+"<p>Christian Gugelmann</p>"+"<p>and Stephan Menzi</p>"+
                "<p>as \"Projekt 1\"</p>";
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        informationLabel = new javax.swing.JLabel();

        setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(informationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(informationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 235, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel informationLabel;
    // End of variables declaration//GEN-END:variables


}
